// ASTERA 탐구 콘텐츠 목데이터.
// 지금은 코드에 직접 정의되어 있지만, 콘텐츠 양이 늘어나면 이 파일 구조를 그대로
// Supabase의 lessons 테이블로 옮기고 여기 대신 DB 조회로 바꾸면 됩니다.

export const AGE_GROUPS = ["전체", "7-9세", "10-12세", "13-17세"];

export const JOURNEY_STEPS = ["질문", "발견", "연결", "검증", "창조", "ASTERA LAB", "공유", "성찰"];

export const LAB_TOOLS = [
  { name: "Algorithm Lab", kr: "추천 알고리즘 설계해요" },
  { name: "Planet Explorer", kr: "행성을 탐사해요" },
  { name: "Future Simulator", kr: "미래를 시뮬레이션해요" },
  { name: "Build Lab", kr: "구조를 설계해요" },
];

export const EXPLORE_ITEMS = [
  {
    slug: "alone-in-universe",
    code: "ASTERA SCIENCE 001",
    universe: "SCIENCE",
    universeKr: "과학",
    ageGroup: "10-12세",
    tags: ["과학", "지구와 우주", "생명"],
    title: "우주에 우리만 살고 있을까?",
    subtitle: "지구 밖에도 생명체가 있을까? 과학자들의 단서를 따라 우주를 탐험하고, 나만의 가설을 세워보세요.",
    image: "/images/earth.webp",
    views: 12300,
    likes: 1200,
    intro:
      "밤하늘의 수많은 별 중 지구와 비슷한 행성이 있다면 어떨까요? 이 탐구에서는 과학자들이 외계 생명체의 흔적을 어떻게 찾는지, 그리고 생명이 살아가려면 무엇이 필요한지 함께 살펴봅니다.",
    preview: "탐구를 시작하면 실제 외계행성 탐사 자료를 바탕으로 한 3단계 미션과 미니 워크시트를 만나볼 수 있어요.",
    goals: ["생명체가 존재하기 위한 최소 조건을 설명할 수 있다.", "외계행성과 지구를 두 가지 이상 기준으로 비교할 수 있다.", "과학적 근거와 상상을 구분해서 말할 수 있다."],
    teacher: "수업 전 발문, 모둠 토론 가이드, 평가 루브릭이 교사용 자료로 제공될 예정입니다.",
    steps: [
      { n: 1, label: "질문", title: "우주에 우리만 살고 있을까?", desc: "질문을 정확히 이해하고 나만의 예상을 적어봅니다.", image: "/images/hero.webp" },
      { n: 2, label: "발견", title: "생명체가 살 수 있는 조건", desc: "물, 온도, 대기 등 생명 조건을 자료로 확인합니다.", image: "/images/earth.webp" },
      { n: 3, label: "연결", title: "지구와 다른 행성 비교", desc: "지구와 후보 행성들의 공통점과 차이점을 비교합니다.", image: "/images/map.webp" },
    ],
  },
  {
    slug: "ai-friend",
    code: "ASTERA THINK 002",
    universe: "TECH",
    universeKr: "기술",
    ageGroup: "7-9세",
    tags: ["철학", "AI", "관계"],
    title: "AI도 친구가 될 수 있을까?",
    subtitle: "친구의 조건, 감정, 인공지능을 하나의 질문으로 연결합니다.",
    image: "/images/lab.webp",
    views: 8400,
    likes: 940,
    intro: "AI가 사람처럼 대화해도 정말 친구라고 부를 수 있을까요? 친구의 조건부터 함께 생각해봅니다.",
    preview: "짧은 대화 시나리오를 읽고 '이건 친구일까?'를 판단해보는 미션으로 시작합니다.",
    goals: ["친구 관계의 핵심 조건을 스스로 정의할 수 있다.", "AI와의 상호작용과 사람 사이의 우정을 비교할 수 있다."],
    teacher: "저학년 발문 카드와 역할극 활동지가 제공될 예정입니다.",
    steps: [
      { n: 1, label: "질문", title: "AI도 친구가 될 수 있을까?", desc: "질문을 듣고 내 생각을 먼저 적어봅니다.", image: "/images/lab.webp" },
      { n: 2, label: "발견", title: "친구의 조건 찾기", desc: "믿음, 감정, 시간처럼 친구에게 필요한 조건을 찾아봅니다.", image: "/images/wide.webp" },
      { n: 3, label: "연결", title: "AI와 사람 비교하기", desc: "AI와의 대화와 사람과의 우정을 비교해봅니다.", image: "/images/hero.webp" },
    ],
  },
  {
    slug: "money-value",
    code: "ASTERA KNOW 003",
    universe: "ECONOMY",
    universeKr: "경제",
    ageGroup: "10-12세",
    tags: ["경제", "화폐", "신뢰"],
    title: "돈은 왜 가치가 있을까?",
    subtitle: "화폐, 신뢰, 교환과 경제의 기본 원리를 어린이 눈높이로.",
    image: "/images/wide.webp",
    views: 6700,
    likes: 610,
    intro: "종이 한 장과 숫자에 사람들이 왜 가치를 부여할까요? 돈과 신뢰의 관계를 탐색합니다.",
    preview: "물물교환 시뮬레이션으로 시작해 화폐가 왜 만들어졌는지 스스로 발견합니다.",
    goals: ["물물교환의 한계를 설명할 수 있다.", "화폐가 성립하기 위한 '신뢰'의 역할을 이해한다."],
    teacher: "모의 시장 놀이 활동지가 함께 제공됩니다.",
    steps: [
      { n: 1, label: "질문", title: "돈은 왜 가치가 있을까?", desc: "돈이 없다면 어떻게 물건을 바꿀지 상상해봅니다.", image: "/images/wide.webp" },
      { n: 2, label: "발견", title: "물물교환의 불편함", desc: "직접 교환을 시도하며 화폐가 필요한 이유를 찾습니다.", image: "/images/map.webp" },
      { n: 3, label: "연결", title: "신뢰와 화폐 제도", desc: "국가와 은행이 화폐 신뢰를 어떻게 지키는지 알아봅니다.", image: "/images/earth.webp" },
    ],
  },
  {
    slug: "bridge-design",
    code: "ASTERA MAKE 004",
    universe: "ENGINEERING",
    universeKr: "공학",
    ageGroup: "10-12세",
    tags: ["공학", "구조", "설계"],
    title: "가장 튼튼한 다리는 어떻게 만들까?",
    subtitle: "구조·압축력·인장력을 배우고 직접 다리를 설계하고 시험합니다.",
    image: "/images/map.webp",
    views: 9100,
    likes: 1050,
    intro: "왜 어떤 다리는 더 튼튼할까요? 삼각형 구조와 트러스, 힘의 분산 원리를 배우고 직접 설계하며 개선합니다.",
    preview: "워크북 멤버십에서 전체 설계 워크시트를 이용할 수 있어요.",
    goals: ["압축력과 인장력의 차이를 설명할 수 있다.", "삼각형 구조가 튼튼한 이유를 구조적으로 설명할 수 있다."],
    teacher: "종이·빨대 다리 만들기 실습 가이드가 제공됩니다.",
    steps: [
      { n: 1, label: "질문", title: "가장 튼튼한 다리는 어떻게 만들까?", desc: "다리가 무너지는 순간을 상상하며 질문을 구체화합니다.", image: "/images/map.webp" },
      { n: 2, label: "발견", title: "압축력과 인장력", desc: "다리의 어느 부분이 눌리고 늘어나는지 관찰합니다.", image: "/images/lab.webp" },
      { n: 3, label: "연결", title: "실제 다리 구조 비교", desc: "한강대교, 금문교 등 실제 다리의 구조를 찾아봅니다.", image: "/images/wide.webp" },
    ],
    workbookSlug: true,
  },
  {
    slug: "fake-news",
    code: "ASTERA CHECK 005",
    universe: "TECH",
    universeKr: "미디어",
    ageGroup: "13-17세",
    tags: ["미디어", "리터러시", "AI"],
    title: "이 뉴스, 진짜일까?",
    subtitle: "AI 시대에 꼭 필요한 어린이 미디어 리터러시 미션.",
    image: "/images/hero.webp",
    views: 5200,
    likes: 480,
    intro: "제목만 보고 믿지 않고 출처·날짜·근거·다른 보도를 확인하는 방법을 연습합니다.",
    preview: "실제와 유사하게 재구성한 가짜 뉴스 예시로 사실 확인 미션을 진행합니다.",
    goals: ["출처와 날짜를 확인하는 습관을 기른다.", "하나의 사건을 다룬 여러 보도를 비교할 수 있다."],
    teacher: "미디어 리터러시 체크리스트가 교사용 자료로 제공됩니다.",
    steps: [
      { n: 1, label: "질문", title: "이 뉴스, 진짜일까?", desc: "의심스러운 제목을 보고 먼저 판단해봅니다.", image: "/images/hero.webp" },
      { n: 2, label: "발견", title: "출처와 근거 확인", desc: "누가, 언제, 무엇을 근거로 썼는지 확인합니다.", image: "/images/lab.webp" },
      { n: 3, label: "연결", title: "다른 보도와 비교", desc: "같은 사건을 다룬 다른 기사와 비교해봅니다.", image: "/images/wide.webp" },
    ],
  },
  {
    slug: "white-lie",
    code: "ASTERA THINK 006",
    universe: "HUMAN",
    universeKr: "인간",
    ageGroup: "7-9세",
    tags: ["철학", "윤리", "관계"],
    title: "친구를 위해 거짓말해도 될까?",
    subtitle: "정답보다 이유를 말하는 연습. 찬성과 반대를 모두 경험합니다.",
    image: "/images/wide.webp",
    views: 4300,
    likes: 390,
    intro: "착한 거짓말도 거짓말일까요? 결과와 의도 중 무엇이 더 중요한지 토론합니다.",
    preview: "찬성/반대 입장을 모두 경험해보는 짧은 토론 시나리오로 시작합니다.",
    goals: ["결과와 의도라는 두 가지 관점을 구분할 수 있다.", "다른 사람의 입장에서 이유를 설명할 수 있다."],
    teacher: "찬반 역할극 대본이 교사용 자료로 제공됩니다.",
    steps: [
      { n: 1, label: "질문", title: "친구를 위해 거짓말해도 될까?", desc: "찬성과 반대 중 내 입장을 먼저 정해봅니다.", image: "/images/wide.webp" },
      { n: 2, label: "발견", title: "의도와 결과", desc: "좋은 의도와 나쁜 결과가 함께일 때를 생각해봅니다.", image: "/images/earth.webp" },
      { n: 3, label: "연결", title: "반대 입장 경험하기", desc: "내 입장과 반대되는 이유를 찾아 말해봅니다.", image: "/images/map.webp" },
    ],
  },
  {
    slug: "urban-heat",
    code: "ASTERA KNOW 007",
    universe: "SCIENCE",
    universeKr: "지구과학",
    ageGroup: "10-12세",
    tags: ["지구", "기후", "도시"],
    title: "도시는 왜 더 더울까?",
    subtitle: "열섬현상과 기후적응을 생활 속 사례로 이해합니다.",
    image: "/images/earth.webp",
    views: 3900,
    likes: 320,
    intro: "도시의 콘크리트와 아스팔트가 열을 머금는 이유를 알아보고 더 시원한 도시를 상상합니다.",
    preview: "우리 동네 사진을 보고 열이 모이는 곳을 찾아보는 미션으로 시작합니다.",
    goals: ["열섬현상이 생기는 이유를 설명할 수 있다.", "도시를 시원하게 만드는 아이디어를 제안할 수 있다."],
    teacher: "동네 답사 활동지가 함께 제공됩니다.",
    steps: [
      { n: 1, label: "질문", title: "도시는 왜 더 더울까?", desc: "도시와 시골의 더위를 비교하며 질문을 떠올립니다.", image: "/images/earth.webp" },
      { n: 2, label: "발견", title: "열섬현상 원인 찾기", desc: "아스팔트, 자동차, 에어컨 등 원인을 찾아봅니다.", image: "/images/lab.webp" },
      { n: 3, label: "연결", title: "시원한 도시 상상하기", desc: "옥상 정원, 그늘 등 해결 아이디어를 연결합니다.", image: "/images/wide.webp" },
    ],
  },
];

export function getExploreItem(slug) {
  return EXPLORE_ITEMS.find((item) => item.slug === slug) || null;
}
